# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# 当名为markdown分支更改的时候，执行该工作流
on:
  push:
    branches: [ markdown ]
  pull_request:
    branches: [ markdown ]


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:12
    steps:
    - uses: actions/checkout@v2
    - run: npm i -g github-markdown
    - run: rm -rf .git
    - run: bash ./transfer.sh
    - run: git init
    - run: git config user.name "sunmaoxiang"
    - run: git config user.email "sunmaoxiang98@163.com"
    - run: git checkout -b main
    - run: git add .
    - run: git commit -m "update note"
    - env:
        TOKEN: ${{ secrets.TOKEN }}
      run: git push --force https://$TOKEN@github.com/sunmaoxiang/sunmaoxiang.github.io.git main